apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: taft
  name: client-taft-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-taft-pod
  template:
    metadata:
      labels:
        app: client-taft-pod
    spec:
      containers:
        - name: proj-schedular
          image: taftallen/schedular-client:2
          ports:
            - containerPort: 5173
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 30
            periodSeconds: 20