apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: taft
  name: client-taft-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: "schedular-app.duckdns.org"
      http:
        paths:
          - path: /taft
            pathType: Prefix
            backend:
              service:
                name: client-taft-svc
                port:
                  number: 5173