apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: taft
  name: server-taft-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: schedular-app.duckdns.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: server-taft-svc
                port:
                  number: 80